# 1. 授权码模式
### 1.1. 申请授权码
GET http://localhost:9999/microservice-auth/oauth/authorize?client_id=client&response_type=code
Authorization: Basic admin 123456

### 1.2. 获取访问令牌
POST  http://localhost:9999/microservice-auth/oauth/token?grant_type=authorization_code&code=XByBIN
Authorization: Basic client 123456

### 2. 密码模式
POST http://localhost:9999/microservice-auth/oauth/token?grant_type=password&username=admin&password=123456
Authorization: Basic client 123456

### 3. 简化模式
GET http://localhost:9999/microservice-auth/oauth/authorize?client_id=client&response_type=token
Authorization: Basic admin 123456

### 4. 客户端模式
POST http://localhost:9999/microservice-auth/oauth/token?grant_type=client_credentials
Authorization: Basic client 123456

# 5. 验证码模式，该模式需要先获取验证码，再获取访问令牌
#### 5.1. 获取验证码
GET http://localhost:9999/captcha

#### 5.2. 获取访问令牌
POST http://localhost:9999/microservice-auth/oauth/token?grant_type=captcha&username=admin&password=123456&
    verifyCode=lnz4&verifyCodeKey=75498ca2f1694011b2eb7c913cb5213a
Authorization: Basic client 123456

### 刷新令牌
POST http://localhost:9999/microservice-auth/oauth/token?grant_type=refresh_token&
    refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbImFsbCJdLCJhdGkiOiJxeEQ0eGEza3JqbnlybW9DWlpkdjViQU9Jb00iLCJleHAiOjE3MDIwMTczNzQsInVzZXJJZCI6MSwiYXV0aG9yaXRpZXMiOlsiYWRtaW4iXSwianRpIjoiS0k4Mm1wREdZV1p2aXc2bXlVem9fYU1GOU04IiwiY2xpZW50X2lkIjoiY2xpZW50IiwidXNlcm5hbWUiOiJhZG1pbiJ9.LSgZmb86ReKjf1gHa8hi6UuHvFmzHHZ_NRQg7t1IR07D1DkSQhSbsml5nEd__ex8WGFIv3n8WFxClXb_UHe1XYr4sWEEEBOjn5wexDheF3XHell4-5YW7t4WNxLeOg6-uNP1lmghmI8LTY7-meMOIlDCROwLNVSRIrOze5rGk1tNalFIFSCNAmh6HRTJXmONT-yVCzjH1m4gYx4Z85LbZpb97BEI_WHO2Unjrqh_wvYLLeBBaUL2cTrYGO0yZDPPoDtmMcqeYhbFRaWZ9ohcTaRP6xBWUhqmeEBgfZFna7L1nCNzR0yUpe4j-PLzI11StTM9Nb4epT1Ar_n-bNNoTQ
Authorization: Basic client 123456

### 获取公钥
GET http://localhost:9999/microservice-auth/rsa/publickey