# 1. 授权码模式
### 1.1. 申请授权码
GET http://localhost:9000/oauth/authorize?client_id=client1&response_type=code
Authorization: Basic admin 123456

### 1.2. 获取访问令牌
POST http://localhost:9000/oauth/token?grant_type=authorization_code&code=BMFAw_
Authorization: Basic client1 123456

### 2. 密码模式
POST http://localhost:9000/oauth/token?grant_type=password&username=admin&password=123456
Authorization: Basic client1 123456

### 3. 简化模式
GET http://localhost:9000/oauth/authorize?client_id=client1&response_type=token
Authorization: Basic admin 123456

### 4. 客户端模式
POST http://localhost:9000/oauth/token?grant_type=client_credentials
Authorization: Basic client1 123456

### 刷新令牌
POST http://localhost:9000/oauth/token?grant_type=refresh_token&
    refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzMSJdLCJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbInNjb3BlMSIsInNjb3BlMiJdLCJhdGkiOiJQUXRTNDZFNlZWV05USlZ4V0J3OXFPT0FlYWsiLCJleHAiOjE3MDE5MzcyNzcsInVzZXJJZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiJdLCJqdGkiOiJMOERraWNRV0tMcENmTjF3cE5uSVFFLVRKTnMiLCJjbGllbnRfaWQiOiJjbGllbnQxIiwidXNlcm5hbWUiOiJhZG1pbiJ9.RJnafA_yQs6GAH3zVhWPwmMeIkeb6iiJTQLI5YVeOXMln1lmGgb7e3hMPQkZyIN125xrNUsvmaGt8n68oTSAiYf01AvkVwaHcaCQWdbh9v1DVMvDpdo7750nfWDURe-KulrKdi28WbbcBsafldYuclHxMqhTADad8O8LV_9t37ueRVw4grHdWcLUaxDNefawbW2Znno4aVAJtSNH-ZgQNcgmRVthXYiCpGWbdLZov3z5EQjfSi7OgLQ9PJMyqNv4i7Lt0cnq7y6gNbO8o3xvwukWjYyMgOdD5ioJoHIu9fW1UsZ7fCAvBSn2Y53YtJPBC3m40UgPoBQ-J2v7Wnlopw
Authorization: Basic client1 123456